server:
  port: 8000

spring:
  profiles:
    active: dev
  application:
    name: gateway
  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            maxAge: 3600
      routes:
        - id: auth-route
          uri: ${AUTH_ROUTE_URI:http://localhost:8001}
          predicates:
            - Path=/auth/**
        - id: user-route
          uri: ${USER_ROUTE_URI:http://localhost:8003}
          predicates:
            - Path=/user/pages/**      